server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      # deserializadores
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      # ao iniciar, só lê novas mensagens (ignora offsets antigos)
      auto-offset-reset: latest

      properties:
        # permite desserializar pacotes do seu app
        spring.json.trusted.packages: "com.scd.notification"
        # desserializar todo value como o DTO local InventoryEvent
        spring.json.value.default.type: com.scd.notification.InventoryEvent
        # não exige cabeçalhos __TypeId__
        spring.json.add.type.headers: false
