server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092

    # === Consumidor (orders → OrderDTO) ===
    consumer:
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"  
        spring.json.value.default.type: com.scd.inventory.InventoryServiceApplication$OrderDTO
        spring.json.add.type.headers: false

      auto-offset-reset: latest

    # === Produtor (inventory-events ← InventoryEvent) ===
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.trusted.packages: "*"  
        spring.json.add.type.headers: false
